# Generated by Django 3.2.3 on 2021-06-18 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
                ('soilt', models.CharField(max_length=20)),
                ('humd', models.FloatField()),
                ('desc', models.CharField(max_length=50)),
                ('precip', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
