# Generated by Django 3.2.3 on 2021-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_location_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cimg', models.ImageField(upload_to='pics')),
                ('cmintemp', models.FloatField(blank=True, null=True)),
                ('cmaxtemp', models.FloatField(blank=True, null=True)),
                ('cminhum', models.FloatField(blank=True, null=True)),
                ('cmaxhum', models.FloatField(blank=True, null=True)),
                ('cminprecip', models.FloatField(blank=True, null=True)),
                ('cmaxprecip', models.FloatField(blank=True, null=True)),
                ('csoiltype', models.CharField(blank=True, max_length=30, null=True)),
                ('croploc', models.ManyToManyField(blank=True, null=True, to='weather.location')),
            ],
        ),
    ]
