# Generated by Django 3.2.3 on 2021-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='croploc',
            field=models.ManyToManyField(blank=True, to='weather.location'),
        ),
    ]
